CREATE TABLE IF NOT EXISTS projects(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL CHECK (name <> ''),
    priority integer NOT NULL,
    description text,
    deliverydate date NOT NULL
);

CREATE TABLE IF NOT EXISTS tasks(
    id intiger PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL CHECK (name <> ''),
    done BOOLEAN,
    projectid integer REFERENCES project(id)
); 

--datos de project
INSERT INTO project(name, priority, description, deliverydate)
    VALUES('MAKE A WEB APP', 1, 'USING JS', '2021-11-01');

INSERT INTO project(name, priority, description, deliverydate)
    VALUES('MAKE AN APP', 1, 'USING DARK', '2021-12-13');

INSERT INTO project(name, priority, description, deliverydate)
    VALUES('DESTOK APP', 1, 'USING JAVA', '2021-01-19');


--datos para task
INSERT INTO task(name, done, projectId)
    VALUES('download Vuejs', false, 1);
    
INSERT INTO task(name, done, projectId)
    VALUES('Create UI', false, 1);

INSERT INTO task(name, done, projectId)
    VALUES('download Flutter', false, 2);

INSERT INTO task(name, done, projectId)
    VALUES('interface desing', false, 2);
